### ISSUE TITLE
Modulation for Inverters

### ISSUE THREAD

**Issue by Jialed0303** [Aalto-Electric-Drives/motulator#63]
This issue aims to develop functionality for the inverter part of ’Motulator’, including a two-level and three-level inverter with the Space Vector Modulation (SVPWM) and over-modulation mode. In addition, to solve unbalanced neutral point voltage problems for the three-level inverter and establish a harmonic analyzer based on a non-uniformed Fourier transform.

**Comment by mhinkkan** [comment]
Many thanks for implementing PWM methods for three-level converters and a nice Master thesis project. This pull-request version is not compatible with the most recent motular version, but I provide here the link to your older version: 

https://github.com/lolo-990303/Motulator_Jiale_oldversion

In order to keep the maintenance efforts feasible, we can't currently include this version in the motulator repository. We are first planning to implement a carrier-comparison based PWM, which would be more compatible with the existing two-level converter models and PWM methods:

https://doi.org/10.1109/IAS.2000.882151
https://doi.org/10.1109/IECON.2012.6389571
https://doi.org/10.23919/IPEC.2018.8507929

We might later come back to your implementation based on space-vector modulation. As we discussed, your thesis work provided many valuable ideas and contributed to our roadmap as well.

@all-contributors please add @Jialed0303 for ideas

**Comment by mhinkkan** [comment]
@all-contributors please add @Jialed0303 for ideas
