### ISSUE TITLE
Looking to simulate BLDC and FOC

### ISSUE THREAD

**Issue by ax-anoop** [Aalto-Electric-Drives/motulator#82]
Hi guys, this is super cool! Thanks for all the hard work to make this project. I'm looking to simulate the following motor 
https://store.cubemars.com/goods-859-RI100+KV105.html and a simple velocity + current controller like > 
![image](https://user-images.githubusercontent.com/95486801/228934208-fb7d9e8d-703c-4b5b-a736-03a952d054fd.png)
 
Before I dive deeper on the control side does the following setup seem okay for the motor? 

```
import numpy as np
import motulator as mt
import math

motor = mt.SynchronousMotor()
mech = mt.Mechanics()
conv = mt.Inverter(u_dc=48)
mdl = mt.SynchronousMotorDrive(motor, mech, conv)

pars = mt.SynchronousMotorVectorCtrlPars(sensorless=False)
pars.n_p = 14 # Pole pairs
pars.L_d = 366.7e-6 # Inductance
pars.L_q = 366.7e-6 # Inductance
pars.R_s = 126e-3   # Stator resistance

pars.psi_f = 60 / (math.sqrt(3) * math.pi * 0.0109 * pars.n_p) # Flux linkage from KT 
pars.J = 215e-6 # Rotor inertia
pars.i_s_max = 1.5*math.sqrt(2) * 5 # 5A max ? 

ctrl = mt.SynchronousMotorVectorCtrl(pars)

## speed controller parameters
speed_kp = 10
speed_ki = 0.1
speed_kt = 1

ctrl.speed_ctrl.k_p = speed_kp
ctrl.speed_ctrl.k_t = speed_kt
ctrl.speed_ctrl.alpha = speed_ki/speed_kt


## Define and run simulation ##
# Speed reference
times = np.array([0, .125, .25, .375, .5, .625, .75, .875, 1])*4
values = np.array([0, 0, 1, 1, 0, -1, -1, 0, 0])
ctrl.w_m_ref = mt.Sequence(times, values)

# External load torque
times = np.array([0, .125, .125, .875, .875, 1])*4
values = np.array([0, 0, 0, 0, 0, 0])
mdl.mech.tau_L_t = mt.Sequence(times, values)

sim = mt.Simulation(mdl, ctrl, pwm=False)
sim.simulate(t_stop=4)
mt.plot(sim)
```

**Comment by lauritapio** [comment]
Hey, 

Thank you for your message. 

Motulator has two sets of parameters.  The first set of parameters are related to the continuous-time motor model, while the second set of parameters are used by the controller. Ideally these would be the same for both (and is often the best starting point for control system analysis), but in practice these are never exactly equal due to several effects, such as temperature variations, inductance saturation and so on.

Note that in your quick example, the parameters of the motor model (class SynchronousMotor) are not set, and thus the default values (corresponding to 2.2-kW permanent-magnet synchronous motor) will be used. 

As for the feasibility of the presented parameters I cannot give much input, the data-sheet of your motor is somewhat dubious. Note that the motor model in motulator is per-phase equivalent, parameters in the datasheet may given in a different format.

Furthermore, the back-electromotive force (b-emf) in some BLDC motors is sinusoidal, and in some motors it is a trapezoid. The synchronous motor model in motulator considers a motor with sinusoidal (back-EMF). To accurately represent motors with trapezoidal b-emf, the default model would need to be extended. Of course, this model assuming a sinusoidal b-emf can be use as an approximation.

**Comment by mhinkkan** [comment]
Thanks you for your comments and for trying this software! 

In the recent releases, we have made the following improvements that are related to this issue:

- Units are added to the docstrings. (Notice that SI units are used throughout the software.)
- By default, 2DOF speed and current controllers are used. However, the user can also configure the control system to use regular 1DOF PI controllers. Please see the classes control.PICtrl and control.ComplexPICtrl, their docstrings and the design notes (https://aalto-electric-drives.github.io/motulator/control/design_notes.html). 
- One example script (https://aalto-electric-drives.github.io/motulator/auto_examples/vector/plot_vector_ctrl_im_2kw.html) now contains a comment how the default speed controller can be replaced with the regular 1DOF speed controller. 
- The 2DOF current controller can be replaced with the 1DOF controller in a similar manner. In the example script mentioned above, you may add, e.g., `ctrl.current_ctrl = control.ComplexPICtrl(k_p=10, k_i=8000)` after you have created the control system object `ctrl`.

I hope that the new features and these comments will help to clarify the control system configuration.

**Comment by ax-anoop** [comment]
@mhinkkan excellent, thanks for the ongoing updates. Will test it out again!

**Comment by ax-anoop** [comment]
One thing that could be helpful is an example of a ~2NM BLDC motor with a cascaded pose/vel controller. This is the typical setup in robotic applications, like universal robotics arms, etc ... If I can get an example like this, I can expand on a few other things that the real world exhibits, i.e, noise in encoders due to either sensor or quantization. & try to provide valuable contributions to the project. The last time I dove deep, I just did not have a grasp over the motor physics sim side to understand if I could simulate a small bldc like the one in the like https://store.tmotor.com/goods-859-RI100+KV105.html

**Comment by mhinkkan** [comment]
If you are interested in encoders and their quantization noise, this master's thesis and references therein could be of interest:

https://aaltodoc.aalto.fi/bitstream/handle/123456789/26720/master_Arslan_Ahmad_2017.pdf

Conributions are welcome!
